### ISSUE TITLE
Gem Ores Render Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [CodersDownUnder/GemsPlusPlus#10]
**Describe the bug**
If a gem ore is placed under the water, it renders incorrectly.

**To Reproduce**
1. Place ores underwater

**Expected behavior**
Ores should render similar to stone or vanilla ores underwater.

**Screenshots**
![2019-09-10_17 33 11](https://user-images.githubusercontent.com/12000593/64658160-0d4ed400-d3fc-11e9-8989-0fc9ef8ea0dc.png)

**Versions**
Minecraft: 1.14.4
GemsPlusPlus: 1.3.1
Forge v28.0.102

**Comment by Trhod17** [comment]
Fixed and uploaded.
