### ISSUE TITLE
Gem Glass Renders Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [CodersDownUnder/GemsPlusPlus#11]
**Describe the bug**
Gem Glass renders incorrectly when placed underwater

**Expected behavior**
Gem Glass should render similarly to Minecraft Glass

**Screenshots**
![2019-10-12_01 52 30](https://user-images.githubusercontent.com/12000593/66696722-f8cc5880-ec93-11e9-8329-23584c51a799.png)

**Versions**
Minecraft: 1.14.4
GemsPlusPlus: 1.3.3

**Comment by Trhod17** [comment]
Fixed and Uploaded
