### ISSUE TITLE
[CF] What happened to the Curseforge page?

### ISSUE THREAD

**Issue by brisingraerowing** [CodersDownUnder/GemsPlusPlus#16]
The Curseforge page seems to have gone missing. What happened?

**Comment by Trhod17** [comment]
it was unapproved because of a link to an external download site (dropbox) it will be fixed soon

**Comment by Trhod17** [comment]
The page is back

**Comment by brisingraerowing** [comment]
That’s good. LittleTiles had the same issue (Dropbox link), but it took 48 hours for Curse to reapprove the page.
