### ISSUE TITLE
Request to add new functionality

### ISSUE THREAD

**Issue by ghost** [CodersDownUnder/GemsPlusPlus#18]
Developer, it would be great if you added the ability to customize the level of ore generation for example Topaz minimum height 100 maximum height 190. this is very necessary. I really need it today.

**Comment by Noob1917** [comment]
developers will you add this or not?

**Comment by Trhod17** [comment]
yes it will be added soon

**Comment by Noob1917** [comment]
can you give me an approximate date?

**Comment by Trhod17** [comment]
maybe later tomorrow if i am not busy or maybe sometime later this week

**Comment by Noob1917** [comment]
how are things going with the addition of this feature?

**Comment by Noob1917** [comment]
@Trhod17 don't ignore give an answer

**Comment by Trhod17** [comment]
I havent been ignoring you ive just been incredibly busy

**Comment by Noob1917** [comment]
Oh, OK. but how's the progress with adding this feature? I really need it

**Comment by Trhod17** [comment]
and i havent had a chance to finish it yet hopefully ill be able to release it tomorrow

**Comment by Noob1917** [comment]
how's it going?

**Comment by Noob1917** [comment]
@Trhod17 well when will the update be? you said "tomorrow" it's been 3 days

**Comment by Trhod17** [comment]
the update will happen when it happens and i said i hope tomorrow but ive run into a issue which completely causes the game to crash on world load and im still trying to fix ore generating in 1.15.1. so be patient

**Comment by Trhod17** [comment]
the functionality has been added
