### ISSUE TITLE
Possible Mod Conflict or Mod Crash

### ISSUE THREAD

**Issue by Camawama** [CodersDownUnder/GemsPlusPlus#19]
Hey there, my name is Alex and I have been trying to put together this Modpack for me and some friends to play on. Your mod works perfectly fine client-side but when running on a server it crashes and doesn't even load the world (like a few other mods I tried installing. I have put together a ZIP file with the Logs, Crash report (if there is one), and the other mods installed with it. I did this for every mod that caused the server to crash and I am contacting developers of the mods in hopes that it's enough information to diagnose the problems. I love to discover bugs and report them so if you ever need some help my discord is Cama#6274

Expected Behaviour is for the server to open without crashing.

Forge Version: Forge-30.0.39
Minecraft Version: 1.15.1
GemsPlus Version: V1.5-Beta-1.15.1

Here is the link to logs and crash report: http://www.mediafire.com/file/t762a811q5zk73z/Gems_Plus.zip/file

**Comment by Trhod17** [comment]
i couldn't see anything in the logs that say that my mod caused the crash nor could i get the a server to crash when running it with all the mods you provided, i recommend trying the gemsplusplus 1.15.1 v1.6 which fixes world gen

**Comment by Camawama** [comment]
I will give that a try

**Comment by Camawama** [comment]
I didn't work, still crashes on startup. I believe there is a Mod Conflict but right now I am working on getting the Modpack to work. I have run into many bugs and errors and I have been trying to get them resolved for a while now. Once I get everything figured out I will test out your Mod again and see if I can get it to work.
