### ISSUE TITLE
Malachite Axe Not Working

### ISSUE THREAD

**Issue by Exavator** [CodersDownUnder/GemsPlusPlus#2]
**Describe the bug**
The malachite axe is not registering as an effective tool for biomes o plenty's fir wood

**To Reproduce**
1. get a malachite axe
2. get a biomes o plenty fir tree
3. try to chop it down, and it is not faster

**Expected behavior**
The malachite axe should be faster to break wood than your hands

**Screenshots**
![2019-05-15_18 18 23](https://user-images.githubusercontent.com/23324366/57819559-dc0c1300-773d-11e9-8f64-7f14abbbdf90.png)
**Forge Version**
14.23.5.2815

**Comment by Trhod17** [comment]
I'll see what i can do to fix it

**Comment by Trhod17** [comment]
I'm releasing the fix in a few minutes
