### ISSUE TITLE
Forge breaks your mod.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [CodersDownUnder/GemsPlusPlus#20]
**Describe the bug**
Mod doesn't load past error screen.

**To Reproduce**
1. run your mod with Forge 1.15.1 - 20.0.51.

**Expected behavior**
That it runs with Forge.

**Screenshots**
N/A

**Versions**
Forge 1.15.1 - 20.0.51
GemsPlusPlus: 1.6 for 1.15.1

**Additional context**
Breaks your mod. Please update. Thanks.

**Comment by Trhod17** [comment]
fixed
