### ISSUE TITLE
After creating an new World Minecraft crashes.

### ISSUE THREAD

**Issue by cyberpunkbln** [CodersDownUnder/GemsPlusPlus#23]
**Describe the bug**
After creating an new World Minecraft crashes.

**To Reproduce**
1. Install GemsPlusPlus standalone
2. Create a new World
3. Minecraft crashes

**Versions**
Minecraft: 1.15.2
Forge: 1.15.2-forge-31.2.0
GemsPlusPlus: gemsplusplus-1.15.2-V1.7.1.jar
[debug.log](https://github.com/CodersDownUnder/GemsPlusPlus/files/4675287/debug.log)

**Comment by Trhod17** [comment]
fixed https://www.curseforge.com/minecraft/mc-mods/gemsplusplus/files/2965207

**Comment by cyberpunkbln** [comment]
Wonderful, thx.
