### ISSUE TITLE
Underground rendering issue

### ISSUE THREAD

**Issue by Sereath** [CodersDownUnder/GemsPlusPlus#24]
**Describe the bug**
Rendering issue with every underground ore block, see the screenshots below.

Started happening ever since we updated to 1.12.2-7.0.1 from 1.12.2-6.2.1.1
Already tried regenerating the config folder and starting a new world.

At first glance from looking at the screenshots you would think that those are air blocks, but they arent. Once you take a closer look you can see that they are indeed GemsPlusPlus ores, you can still interact with them.

**Expected behavior**
Ore blocks don't usually render every single place they occupy while underground, be it vanilla ore blocks or modded ones.

**Screenshots**
![image](https://user-images.githubusercontent.com/54506307/83739059-b688ca80-a61a-11ea-9210-01251f01cf66.png)
![image](https://user-images.githubusercontent.com/54506307/83739071-b983bb00-a61a-11ea-8e3b-7c95612bf829.png)
![image](https://user-images.githubusercontent.com/54506307/83739077-bbe61500-a61a-11ea-9699-fd51884414b2.png)
![image](https://user-images.githubusercontent.com/54506307/83739085-be486f00-a61a-11ea-80b3-91b2c1d43e67.png)

Everywhere
![image](https://user-images.githubusercontent.com/54506307/83739500-49c20000-a61b-11ea-8f1f-4cd83c1fd178.png)

**Versions**
Minecraft: 1.12.2
GemsPlusPlus: 7.0.1

**Comment by Trhod17** [comment]
Fixed in V7.0.2

https://www.curseforge.com/minecraft/mc-mods/gemsplusplus/files/2972249
