### ISSUE TITLE
Gems not spawning in 1.16.3

### ISSUE THREAD

**Issue by Argon387** [CodersDownUnder/GemsPlusPlus#26]
Cant find any gems spawning in version 1.16.3-V1.8.0

Using forge-34.1.0
Minecraft: 1.16.3
GemsPlusPlus: 1.8.0

**Comment by Trhod17** [comment]
I cant recreate this issue on my end can you try updating forge to the latest available version

**Comment by Argon387** [comment]
Apologies, you're right, I used an xray mod to see them, and they are there. They seem to be spawning much fewer than the previous version, I'll play around with the config, thanks.
