### ISSUE TITLE
Crash client side when wearing armor on server

### ISSUE THREAD

**Issue by Davidux22** [CodersDownUnder/GemsPlusPlus#3]
When i try to wear an armor on a server i created with this mod i get kicked out
The only way to "fix it" is to delete the armor piece with nbtExplorer

![mods](https://user-images.githubusercontent.com/24900681/58177383-92bf4480-7ca4-11e9-87db-b2ffd5146142.PNG)
![serverlog](https://user-images.githubusercontent.com/24900681/58177533-dade6700-7ca4-11e9-91a8-23299c8250ac.jpg)

**Forge 1.12.2-14.23.5.2838**

**Comment by Trhod17** [comment]
just release the fix in 5.3.4

**Comment by Davidux22** [comment]
Nice it works now thx ^^ 
![2019-05-23_16 20 34](https://user-images.githubusercontent.com/24900681/58260583-02056900-7d77-11e9-9769-c2062d2fafde.png)
