### ISSUE TITLE
Is the Phoenixite ore not generated in the 1.12.2 mod

### ISSUE THREAD

**Issue by 200542053** [CodersDownUnder/GemsPlusPlus#30]
I used [Just Enough Resources](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer) to generate the ore distribution in 20,000 chunks, gem++ uses the default config. I can't find the generated data for Phoenixite Ore or Nether Phoenixite Ore in the world-gen.json, or maybe just a bug of Just Enough Resources?
Mod version:
JustEnoughResources-1.12.2-0.9.2.60
gemsplusplus-1.12.2-7.0.4
Forge - 14.23.5.2838

[world-gen.json](https://drive.google.com/file/d/1wcqq03gY4nEUxtjhY_20nXanUVdlJ0w2/view?usp=sharing)

**Comment by Trhod17** [comment]
i know phoenixite ore generation works in that version of gemsplusplus so i am just going to say its a bug with just enough resources. also 1.12.2 is no longer supported.
