### ISSUE TITLE
Crash w/ Armory Expansion

### ISSUE THREAD

**Issue by WenXin20** [CodersDownUnder/GemsPlusPlus#6]
Minecraft v1.12.2
Forge v14.23.5.28388
[Armory Expansion](https://www.curseforge.com/minecraft/mc-mods/armory-expansion) v1.3.3
Construct Armory v1.2.4
TConstruct v2.12.0.157
Gems ++ v6.0.5.0

Armory Expansion appears to also add stats to Agate, which is causing a crash with this mod.
[Crash Report](https://paste.dimdev.org/ovicoluwuh.mccrash)

**Comment by Trhod17** [comment]
Just release the update with the fix https://www.curseforge.com/minecraft/mc-mods/gemsplusplus/files/2760805
