### ISSUE TITLE
Allow Ores to Drop Experience

### ISSUE THREAD

**Issue by WenXin20** [CodersDownUnder/GemsPlusPlus#7]
Minecraft v1.12.2
Gems++ v6.1.0.1

Currently, ores don't drop any experience when mined. Adding this could make mining the ores more useful.

**Comment by Trhod17** [comment]
added and uploaded

**Comment by WenXin20** [comment]
Ores in 1.14.4 for Forge v28.1.27 don't drop any experience.

**Comment by Trhod17** [comment]
Feature added and new version uploaded
