### ISSUE TITLE
Phoenixite Ore Texture is Broken

### ISSUE THREAD

**Issue by WenXin20** [CodersDownUnder/GemsPlusPlus#9]
Minecraft v1.14.4
Forge v28.0.100
Gems++ v1.3.0

As seen in the image below, Phoenixite Ore textures for both stone and netherrack is broken. 
![2019-09-09_20 49 05](https://user-images.githubusercontent.com/12000593/64578582-74f61800-d345-11e9-966d-4bf0fc609a7a.png)

**Comment by Trhod17** [comment]
Fixed and uploaded
